entryScript: score.py
sourceDirectory: .
environment:
  docker:
    arguments: []
    baseImage: mcr.microsoft.com/azureml/base:intelmpi2018.3-ubuntu16.04
  environmentVariables:
    EXAMPLE_ENV_VAR: EXAMPLE_VALUE
  name: my-deploy-env
  python:
    condaDependenciesFile: config/inference-conda.yml
  version: '1'
