variables:
  ml-ws-connection: 'edapmlops_aml' # Workspace Service Connection name
  ml-ws: 'edapmlopstest' # AML Workspace name
  ml-rg: 'dev-edap-ml-ops' # AML resource Group name
  ml-ct: 'cpu-cluster-1' # AML Compute cluster name
  ml-path: 'models/diabetes' # Model directory path in repo
  ml-exp: 'aml_devops' # Experiment name
  ml-model-name: 'diabetes-model' # Model name
  ml-aks-name: 'my-aks-9' # AKS cluster name
